name: winsys
description: "winsys package project"
version: 0.0.1
homepage:
repository: https://github.com/lang-library/dart-winsys

environment:
  sdk: ^3.7.2

dependencies:
  output: ^1.0.0
  ffi: ^2.1.4

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.15
